name: Build project
description: Set up the environment and build the project

inputs:
    dotnet-version:
        description: "Version of dotnet"
        required: true
        default: 7.x

runs:
    using: "composite"
    steps:
        -   name: Set up dotnet environment
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: ${{inputs.dotnet-version}}
        -   name: Set up dotnet tools
            run: dotnet tool restore
            shell: bash
        -   name: Build dotnet solution
            run: dotnet build .
            shell: bash