name: Continuous Integration

on:
    push:
        paths-ignore:
            - '**.md'
            - LICENSE
        branches:
            - "*"
    pull_request:
        paths-ignore:
            - '**.md'
            - LICENSE
        branches:
            - "*"
    workflow_dispatch:

jobs:
    format:
        name: Verify code format
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout project
                uses: actions/checkout@v3
            -   name: Build project
                uses: ./.github/workflows/build-project
            -   name: Verify code
                run: dotnet format . --verify-no-changes -v d
    test:
        name: Run tests
        runs-on: ubuntu-latest
        needs: format
        steps:
            -   name: Checkout project
                uses: actions/checkout@v3
            -   name: Build project
                uses: ./.github/workflows/build-project
            -   name: Run tests
                run: dotnet test . -l "console;verbosity=detailed" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
            -   name: Run tests with mutations
                run: dotnet stryker -f stryker-config.ci.json
            -   name: Upload coverage
                uses: codacy/codacy-coverage-reporter-action@v1
                with:
                    project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                    coverage-reports: shared-tests/coverage.opencover.xml