name: Continuous Integration

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"
    workflow_dispatch: 

env:
    dotnet-version: 6.0.x

jobs: 
    build:
        name: Build project & run tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Set up dotnet environment
              uses: actions/setup-dotnet@v2
              with: 
                  dotnet-version: ${{env.dotnet-version}}
            - name: Build project
              run: dotnet build .
            - name: Run tests
              run: dotnet test . -l "console;verbosity=detailled"