name: Continuous Integration

on:
    push:
        paths-ignore:
            - '**.md'
            - LICENSE
        branches:
            - "*"
    pull_request:
        paths-ignore:
            - '**.md'
            - LICENSE
        branches:
            - "*"
    workflow_dispatch:

env:
    dotnet-version: 6.0.x

jobs:
    format:
        name: Verify code format
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout project
                uses: actions/checkout@v2
            -   name: Set up dotnet environment
                uses: actions/setup-dotnet@v2
                with:
                    dotnet-version: ${{env.dotnet-version}}
            -   name: Verify code
                run: dotnet format . --verify-no-changes -v d
    test:
        name: Run tests
        runs-on: ubuntu-latest
        needs: format
        steps:
            -   name: Checkout project
                uses: actions/checkout@v2
            -   name: Set up dotnet environment
                uses: actions/setup-dotnet@v2
                with:
                    dotnet-version: ${{env.dotnet-version}}
            -   name: Set up tools
                run: dotnet tool restore
            -   name: Build project
                run: dotnet build .
            -   name: Run tests
                run: dotnet test . -l "console;verbosity=detailed"
            -   name: Run tests with mutations
                run: dotnet stryker -f stryker-config.ci.json